<?php
include_once("index.html");
include_once("style.css");
include_once("script.js");
include_once("arrow.jpg");
include_once("chat_icon.jpg");
include_once("gadgets.jpg");
include_once("logo.gif");
include_once("web_icon.jpg");
?>
